import type { BuiltinThemePreset, Preferences } from './types';

// 默认偏好设置
const DEFAULT_PREFERENCES: Preferences = {
  app: {
    authPageLayout: 'panel-right',
    checkUpdatesInterval: 1,
    colorGrayMode: false,
    colorWeakMode: false,
    compact: false,
    contentCompact: 'wide',
    defaultAvatar:
      'https://unpkg.com/@vbenjs/static-source@0.1.7/source/avatar-v1.webp',
    dynamicTitle: true,
    enableCheckUpdates: true,
    enablePreferences: true,
    enableRefreshToken: false,
    isMobile: false,
    layout: 'sidebar-nav',
    locale: 'zh-CN',
    loginExpiredMode: 'page',
    name: import.meta.env.VITE_APP_TITLE || '中石化知识库',
    preferencesButtonPosition: 'auto',
    watermark: false,
  },
  breadcrumb: {
    enable: true,
    hideOnlyOne: false,
    showHome: true,
    showIcon: true,
    styleType: 'normal',
  },
  copyright: {
    companyName: 'Saas',
    companySiteLink: 'https://www.saas.pro',
    date: '2025',
    enable: true,
    icp: '',
    icpLink: '',
    settingShow: true,
  },
  footer: {
    enable: false,
    fixed: false,
  },
  header: {
    enable: true,
    hidden: false,
    menuAlign: 'start',
    mode: 'fixed',
  },
  logo: {
    enable: true,
    source: 'https://unpkg.com/@vbenjs/static-source@0.1.7/source/logo-v1.webp',
  },
  navigation: {
    accordion: true,
    split: true,
    styleType: 'rounded',
  },
  shortcutKeys: {
    enable: true,
    globalLockScreen: true,
    globalLogout: true,
    globalPreferences: true,
    globalSearch: true,
  },
  sidebar: {
    collapsed: false,
    inverted: false,
    enable: true,
    expandOnHover: true,
    hidden: false,
    width: 224,
  },
  tabbar: {
    draggable: true,
    enable: true,
    height: 38,
    keepAlive: true,
    maxCount: 0,
    middleClickToClose: false,
    persist: true,
    showIcon: true,
    showMaximize: true,
    showMore: true,
    styleType: 'chrome',
    wheelable: true,
  },
  theme: {
    primary: '#2080F0FF',
    info: '#2080F0FF',
    success: '#18A058FF',
    warning: '#F0A020FF',
    error: '#D03050FF',
    builtinType: 'default',
    mode: 'light',
    radius: '0.5',
    semiDarkHeader: false,
    semiDarkSidebar: false,
  },
  transition: {
    enable: true,
    loading: true,
    name: 'fade-slide',
    progress: true,
  },
  widget: {
    fullscreen: true,
    globalSearch: true,
    languageToggle: true,
    lockScreen: true,
    notification: true,
    refresh: true,
    sidebarToggle: true,
    themeToggle: true,
  },
};
// 内置主题预设
const BUILT_IN_THEME_PRESETS: BuiltinThemePreset[] = [
  { color: '#006be6ff', type: 'default' },
  { color: '#7166f0ff', type: 'violet' },
  { color: '#e84a6cff', type: 'pink' },
  { color: '#efbd48ff', type: 'yellow' },
  { color: '#4e69fdff', type: 'sky-blue' },
  { color: '#0bd092ff', type: 'green' },
  { color: '#3f3f46ff', type: 'zinc' },
  { color: '#0d9496ff', type: 'deep-green' },
  { color: '#0960beff', type: 'deep-blue' },
  { color: '#c1420bff', type: 'orange' },
  { color: '#bb1b1bff', type: 'rose' },
  { color: '#404040ff', type: 'neutral' },
  { color: '#344256ff', type: 'slate' },
  { color: '#384252ff', type: 'gray' },
  { color: '', type: 'custom' },
];
// 首页主题预设
const COLOR_PRESETS = [...BUILT_IN_THEME_PRESETS].slice(0, 7);

export { BUILT_IN_THEME_PRESETS, COLOR_PRESETS, DEFAULT_PREFERENCES };
