/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取聊天助手列表 */
        get: operations["AssistantController_findAll"];
        put?: never;
        /** 创建聊天助手 */
        post: operations["AssistantController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/general": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 获取或创建当前用户的通用助手 */
        post: operations["AssistantController_getOrCreateGeneral"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取聊天助手详情 */
        get: operations["AssistantController_findOne"];
        put?: never;
        post?: never;
        /** 删除聊天助手 */
        delete: operations["AssistantController_remove"];
        options?: never;
        head?: never;
        /** 更新聊天助手 */
        patch: operations["AssistantController_update"];
        trace?: never;
    };
    "/api/assistant/{id}/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 向指定的聊天助手提问以开始 AI 驱动的对话（SSE 流式响应） */
        post: operations["AssistantController_completions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/{id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取与聊天助手的会话列表 */
        get: operations["AssistantController_findAllSessions"];
        put?: never;
        /** 创建与聊天助手的会话 */
        post: operations["AssistantController_createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/{id}/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除与聊天助手的会话 */
        delete: operations["AssistantController_removeSession"];
        options?: never;
        head?: never;
        /** 更新与聊天助手的会话 */
        patch: operations["AssistantController_updateSession"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssistantEntity: {
            /** @description 外部助手 ID */
            assistantId: string | null;
            /** @description 助手头像 URL */
            avatar: string | null;
            /**
             * Format: date-time
             * @description 创建时间
             */
            createdAt: string;
            /** @description RAGFlow 关联的数据集ID列表 */
            datasetIds: string[];
            /** @description 所属部门ID（仅 permission="team" 时有意义） */
            deptId: number | null;
            /** @description 助手描述 */
            description: string | null;
            /** @description 空响应返回内容 */
            emptyResponse: string | null;
            /** @description 频率惩罚 */
            frequencyPenalty: number;
            /** @description 主键 ID */
            id: number;
            /** @description 是否为通用助手 */
            isGeneral: boolean;
            /** @description 关键词相似度权重 */
            keywordsSimilarityWeight: number;
            /** @description 最大生成长度 */
            maxTokens: number;
            /** @description 聊天模型名称 */
            modelName: string;
            /** @description 助手名称 */
            name: string;
            /** @description 开场问候语 */
            opener: string | null;
            /** @description 访问权限：me 仅自己 / team 本部门 / public 全公司 */
            permission: string;
            /** @description 存在惩罚 */
            presencePenalty: number;
            /** @description 提示词模板 */
            prompt: string | null;
            /** @description 加权关键字相似度 */
            similarityThreshold: number;
            /** @description 温度 */
            temperature: number;
            /** @description 重新排序或选择前 k 个项目 */
            topK: number;
            /** @description 生成的回复数量 */
            topN: number;
            /** @description 核心采样 */
            topP: number;
            /**
             * Format: date-time
             * @description 更新时间
             */
            updatedAt: string;
            /** @description 所属用户 ID */
            userId: number;
        };
        CreateAssistantDto: {
            /**
             * @description 助手头像
             * @example https://example.com/avatar.png
             */
            avatar?: string;
            /**
             * @description 关联的知识库数据集 ID 列表（RAGFlow datasetId）
             * @example [
             *       "dataset_id_1",
             *       "dataset_id_2"
             *     ]
             */
            datasetIds?: string[];
            /**
             * @description 助手描述
             * @example 这是一个智能助手
             */
            description?: string;
            /**
             * @description 空响应返回内容
             * @example 无
             */
            emptyResponse?: string;
            /**
             * @description 频率惩罚
             * @example 0.7
             */
            frequencyPenalty?: number;
            /**
             * @description 关键词相似度权重
             * @example 0.7
             */
            keywordsSimilarityWeight?: number;
            /**
             * @description 最大生成长度
             * @example 512
             */
            maxTokens?: number;
            /**
             * @description 聊天模型名称（格式: model_name@provider）
             * @example deepseek-r1@Xinference
             */
            modelName?: string;
            /**
             * @description 助手名称
             * @example 助手1
             */
            name: string;
            /**
             * @description 开场问候语
             * @example 你好，我是你的助手。
             */
            opener?: string;
            /**
             * @description 助手访问权限：me 仅自己 / team 本部门 / public 全公司
             * @example me
             * @enum {string}
             */
            permission?: "me" | "team" | "public";
            /**
             * @description 存在惩罚
             * @example 0.4
             */
            presencePenalty?: number;
            /**
             * @description 提示词模板
             * @example <prompt>
             */
            prompt?: string;
            /**
             * @description 加权关键字相似度
             * @example 0.2
             */
            similarityThreshold?: number;
            /**
             * @description 温度
             * @example 0.1
             */
            temperature?: number;
            /**
             * @description 重新排序或选择前 k 个项目
             * @example 1024
             */
            topK?: number;
            /**
             * @description 生成的回复数量
             * @example 6
             */
            topN?: number;
            /**
             * @description 核心采样
             * @example 0.3
             */
            topP?: number;
        };
        CreateCompletionsDto: {
            /**
             * @description 开始人工智能对话的问题
             * @example 你好
             */
            question: string;
            /**
             * @description 会话ID
             * @example session_id
             */
            sessionId?: string;
            /**
             * @description 是否开启流式响应
             * @example true
             */
            stream?: boolean;
        };
        CreateSessionDto: {
            /**
             * @description 会话名称
             * @example 会话1
             */
            name?: string;
        };
        PaginateResponse: {
            /**
             * @description 页码
             *     @default 1
             * @default 1
             * @example 1
             */
            current: number;
            /**
             * @description 每页数量
             *     @default 10
             * @default 10
             * @example 10
             */
            pageSize: number;
        };
        ReferenceChunkEntity: {
            /** @description 块文本内容 */
            content: string;
            /** @description 数据集 ID */
            dataset_id: string;
            /** @description 文档类型 */
            doc_type: string;
            /** @description 文档 ID */
            document_id: string;
            /** @description 文档名称 */
            document_name: string;
            /** @description 块 ID */
            id: string;
            /** @description 关联图片 ID */
            image_id: string;
            positions: number[][];
            /** @description 综合相似度（0~1） */
            similarity: number;
            /** @description 关键词相似度 */
            term_similarity: number;
            /** @description 关联资源 URL */
            url: string | null;
            /** @description 向量相似度 */
            vector_similarity: number;
        };
        ReferenceDocAggEntity: {
            /** @description 该文档被引用的块数 */
            count: number;
            /** @description 文档 ID */
            doc_id: string;
            /** @description 文档名称 */
            doc_name: string;
        };
        ReferenceEntity: {
            /** @description 命中的引用块列表 */
            chunks: components["schemas"]["ReferenceChunkEntity"][];
            /** @description 文档维度的聚合统计 */
            doc_aggs: components["schemas"]["ReferenceDocAggEntity"][];
        };
        SessionEntity: {
            /** @description 关联的助手聊天 ID */
            chatId: string;
            /** @description 创建日期 */
            createDate: string;
            /** @description 会话 ID */
            id: string;
            /** @description 消息列表 */
            messages: components["schemas"]["SessionMessageEntity"][];
            /** @description 会话名称 */
            name: string;
            /** @description 更新日期 */
            updateDate: string;
        };
        SessionMessageEntity: {
            /** @description 消息内容 */
            content: string;
            /** @description 引用数据（assistant 消息可能包含，由 RAGFlow 在答复时返回） */
            reference?: components["schemas"]["ReferenceEntity"];
            /** @description 消息角色 */
            role: string;
        };
        UpdateAssistantDto: {
            /**
             * @description 助手头像
             * @example https://example.com/avatar.png
             */
            avatar?: string;
            /**
             * @description 关联的知识库数据集 ID 列表（RAGFlow datasetId）
             * @example [
             *       "dataset_id_1",
             *       "dataset_id_2"
             *     ]
             */
            datasetIds?: string[];
            /**
             * @description 助手描述
             * @example 这是一个智能助手
             */
            description?: string;
            /**
             * @description 空响应返回内容
             * @example 无
             */
            emptyResponse?: string;
            /**
             * @description 频率惩罚
             * @example 0.7
             */
            frequencyPenalty?: number;
            /**
             * @description 关键词相似度权重
             * @example 0.7
             */
            keywordsSimilarityWeight?: number;
            /**
             * @description 最大生成长度
             * @example 512
             */
            maxTokens?: number;
            /**
             * @description 聊天模型名称（格式: model_name@provider）
             * @example deepseek-r1@Xinference
             */
            modelName?: string;
            /**
             * @description 助手名称
             * @example 助手1
             */
            name?: string;
            /**
             * @description 开场问候语
             * @example 你好，我是你的助手。
             */
            opener?: string;
            /**
             * @description 助手访问权限：me 仅自己 / team 本部门 / public 全公司
             * @example me
             * @enum {string}
             */
            permission?: "me" | "team" | "public";
            /**
             * @description 存在惩罚
             * @example 0.4
             */
            presencePenalty?: number;
            /**
             * @description 提示词模板
             * @example <prompt>
             */
            prompt?: string;
            /**
             * @description 加权关键字相似度
             * @example 0.2
             */
            similarityThreshold?: number;
            /**
             * @description 温度
             * @example 0.1
             */
            temperature?: number;
            /**
             * @description 重新排序或选择前 k 个项目
             * @example 1024
             */
            topK?: number;
            /**
             * @description 生成的回复数量
             * @example 6
             */
            topN?: number;
            /**
             * @description 核心采样
             * @example 0.3
             */
            topP?: number;
        };
        UpdateSessionDto: {
            /**
             * @description 会话名称
             * @example 会话1
             */
            name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AssistantController_findAll: {
        parameters: {
            query?: {
                /**
                 * @description 页码
                 *     @default 1
                 */
                current?: number;
                /**
                 * @description 每页数量
                 *     @default 10
                 */
                pageSize?: number;
                /** @description 助手名称 */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginateResponse"] & {
                        /** @default 1 */
                        currentPage: number;
                        /** @default [] */
                        list: components["schemas"]["AssistantEntity"][];
                        /** @default 0 */
                        pageCount: number;
                        /** @default 0 */
                        totalCount: number;
                    };
                };
            };
        };
    };
    AssistantController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssistantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantEntity"];
                };
            };
        };
    };
    AssistantController_getOrCreateGeneral: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantEntity"];
                };
            };
        };
    };
    AssistantController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantEntity"];
                };
            };
        };
    };
    AssistantController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssistantController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssistantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantEntity"];
                };
            };
        };
    };
    AssistantController_completions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompletionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEntity"];
                };
            };
        };
    };
    AssistantController_findAllSessions: {
        parameters: {
            query?: {
                /** @description 会话名称 */
                name?: string;
                /** @description 页码 */
                page?: number;
                /** @description 每页数量 */
                pageSize?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEntity"][];
                };
            };
        };
    };
    AssistantController_createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEntity"];
                };
            };
        };
    };
    AssistantController_removeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEntity"];
                };
            };
        };
    };
    AssistantController_updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEntity"];
                };
            };
        };
    };
}
