/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/knowledge-base": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取知识库列表 */
        get: operations["KnowledgeBaseController_findAll"];
        put?: never;
        /** 创建知识库 */
        post: operations["KnowledgeBaseController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/llms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 RAGFlow 已配置的 LLM 模型列表 */
        get: operations["LlmController_getLlmList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["KnowledgeBaseController_retrieveChunks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取知识库详情 */
        get: operations["KnowledgeBaseController_findOne"];
        put?: never;
        post?: never;
        /** 删除知识库 */
        delete: operations["KnowledgeBaseController_remove"];
        options?: never;
        head?: never;
        /** 更新知识库 */
        patch: operations["KnowledgeBaseController_update"];
        trace?: never;
    };
    "/api/knowledge-base/{id}/backfill-keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["KnowledgeBaseController_backfillKeywords"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["KnowledgeBaseController_findAllDocuments"];
        put?: never;
        /** 上传文件到指定知识库 */
        post: operations["KnowledgeBaseController_uploadDocuments"];
        /** 删除知识库文件 */
        delete: operations["KnowledgeBaseController_removeDocuments"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/{id}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载知识库文件 */
        get: operations["KnowledgeBaseController_downloadDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新知识库文件 */
        patch: operations["KnowledgeBaseController_updateDocument"];
        trace?: never;
    };
    "/api/knowledge-base/{id}/documents/{documentId}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取分块列表 */
        get: operations["KnowledgeBaseController_findAllChunks"];
        put?: never;
        /** 添加分块 */
        post: operations["KnowledgeBaseController_addChunk"];
        /** 删除分块 */
        delete: operations["KnowledgeBaseController_removeChunks"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/{id}/documents/{documentId}/chunks/{chunkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新分块 */
        put: operations["KnowledgeBaseController_updateChunk"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/{id}/documents/{documentId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 切换知识库文档启用状态 */
        patch: operations["KnowledgeBaseController_toggleDocumentStatus"];
        trace?: never;
    };
    "/api/knowledge-base/{id}/keyword-tag-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 管理员查看知识库打 tag 待办状态 */
        get: operations["KnowledgeBaseController_keywordTagStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/{id}/metadata/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取知识库元数据摘要 */
        get: operations["KnowledgeBaseController_getMetadataSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-base/{id}/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 解析指定知识库中的文件 */
        post: operations["KnowledgeBaseController_parseDocuments"];
        /** 停止解析指定知识库中的文件 */
        delete: operations["KnowledgeBaseController_stopParseDocuments"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddChunkDto: {
            /**
             * @description 分块内容
             * @example 这是一段分块内容
             */
            content: string;
            /**
             * @description 关键词
             * @example [
             *       "关键词1",
             *       "关键词2"
             *     ]
             */
            importantKeywords?: string[];
            /**
             * @description 问题列表
             * @example [
             *       "问题1"
             *     ]
             */
            questions?: string[];
        };
        CreateKnowledgeBaseDto: {
            /**
             * @description 知识库头像（Base64）
             * @example https://example.com/avatar.png
             */
            avatar?: string;
            /**
             * @description 解析方法
             * @default naive
             * @example naive
             */
            chunkMethod: string;
            /**
             * @description 描述
             * @example 这是一个知识库
             */
            description?: string;
            /**
             * @description 嵌入模型（格式: model_name@provider）
             * @example bge-large-zh-v1.5@Xinference
             */
            embeddingModel?: string;
            /**
             * @description 知识库名称
             * @example 知识库1
             */
            name: string;
            /**
             * @description 排序
             * @example 1
             */
            order?: number;
            /**
             * @description 权限标识
             * @example me
             * @enum {string}
             */
            permission?: "me" | "team" | "public";
        };
        DeleteChunkDto: {
            /**
             * @description 分块ID列表
             * @example [
             *       "chunk_id_1",
             *       "chunk_id_2"
             *     ]
             */
            chunkIds: string[];
        };
        DeleteDocumentDto: {
            /**
             * @description 文件ID列表
             * @example [
             *       "78e5ae6691db11f084d3fa341edb7c4d"
             *     ]
             */
            documentIds: string[];
        };
        FilesUploadDto: {
            /** @description 上传的文件列表 */
            files: string[];
            /**
             * @description 文件类型
             * @example images
             * @enum {string}
             */
            type: "audios" | "images" | "videos";
        };
        KnowledgeBaseEntity: {
            avatar: string | null;
            chunkMethod: string;
            createBy: string;
            /** Format: date-time */
            createdAt: string;
            datasetId: string | null;
            deptId: number | null;
            description: string | null;
            embeddingModel: string;
            id: number;
            name: string;
            order: number;
            parserConfig: Record<string, never>;
            permission: string | null;
            updateBy: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginateResponse: {
            /**
             * @description 页码
             *     @default 1
             * @default 1
             * @example 1
             */
            current: number;
            /**
             * @description 每页数量
             *     @default 10
             * @default 10
             * @example 10
             */
            pageSize: number;
        };
        ParseDocumentDto: {
            /**
             * @description 文件ID列表
             * @example [
             *       "78e5ae6691db11f084d3fa341edb7c4d"
             *     ]
             */
            documentIds: string[];
        };
        RetrieveChunkDto: {
            /**
             * @description 数据集ID列表
             * @example [
             *       "dataset_id_1"
             *     ]
             */
            datasetIds?: string[];
            /**
             * @description 文档ID列表
             * @example [
             *       "document_id_1"
             *     ]
             */
            documentIds?: string[];
            /**
             * @description 是否高亮
             * @example false
             */
            highlight?: boolean;
            /**
             * @description 页码
             * @example 1
             */
            page?: number;
            /**
             * @description 每页数量
             * @example 30
             */
            pageSize?: number;
            /**
             * @description 检索问题
             * @example 什么是RAGFlow?
             */
            question: string;
            /**
             * @description 相似度阈值
             * @example 0.2
             */
            similarityThreshold?: number;
            /**
             * @description Top K
             * @example 1024
             */
            topK?: number;
            /**
             * @description 是否使用知识图谱
             * @example false
             */
            useKg?: boolean;
            /**
             * @description 向量相似度权重
             * @example 0.3
             */
            vectorSimilarityWeight?: number;
        };
        ToggleDocumentStatusDto: {
            /**
             * @description 文档启用状态 ('1' 启用, '0' 禁用)
             * @example 1
             */
            status: string;
        };
        UpdateChunkDto: {
            /**
             * @description 是否可用
             * @example true
             */
            available?: boolean;
            /**
             * @description 分块内容
             * @example 更新后的分块内容
             */
            content?: string;
            /**
             * @description 关键词
             * @example [
             *       "关键词1",
             *       "关键词2"
             *     ]
             */
            importantKeywords?: string[];
        };
        UpdateDocumentDto: {
            /**
             * @description 解析方法
             * @example naive
             */
            chunkMethod?: string;
            /**
             * @description 文档名称
             * @example 文档1
             */
            name?: string;
        };
        UpdateKnowledgeBaseDto: {
            /**
             * @description 知识库头像（Base64）
             * @example https://example.com/avatar.png
             */
            avatar?: string;
            /**
             * @description 解析方法
             * @default naive
             * @example naive
             */
            chunkMethod: string;
            /**
             * @description 描述
             * @example 这是一个知识库
             */
            description?: string;
            /**
             * @description 知识库名称
             * @example 知识库1
             */
            name?: string;
            /**
             * @description 排序
             * @example 1
             */
            order?: number;
            /**
             * @description 权限标识
             * @example me
             * @enum {string}
             */
            permission?: "me" | "team" | "public";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    KnowledgeBaseController_findAll: {
        parameters: {
            query?: {
                /**
                 * @description 页码
                 *     @default 1
                 */
                current?: number;
                /**
                 * @description 每页数量
                 *     @default 10
                 */
                pageSize?: number;
                /** @description 知识库名称 */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginateResponse"] & {
                        /** @default 1 */
                        currentPage: number;
                        /** @default [] */
                        list: components["schemas"]["KnowledgeBaseEntity"][];
                        /** @default 0 */
                        pageCount: number;
                        /** @default 0 */
                        totalCount: number;
                    };
                };
            };
        };
    };
    KnowledgeBaseController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKnowledgeBaseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseEntity"];
                };
            };
        };
    };
    LlmController_getLlmList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回已配置的 LLM 模型列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeBaseController_retrieveChunks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrieveChunkDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseEntity"];
                };
            };
        };
    };
    KnowledgeBaseController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeBaseController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateKnowledgeBaseDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseEntity"];
                };
            };
        };
    };
    KnowledgeBaseController_backfillKeywords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeBaseController_findAllDocuments: {
        parameters: {
            query?: {
                /** @description 文档名称 */
                name?: string;
                /** @description 页码 */
                page?: number;
                /** @description 每页数量 */
                pageSize?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_uploadDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description 上传文件 */
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["FilesUploadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_removeDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteDocumentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_downloadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeBaseController_updateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDocumentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_findAllChunks: {
        parameters: {
            query?: {
                /** @description 分块ID */
                id?: string;
                /** @description 搜索关键词 */
                keywords?: string;
                /** @description 页码 */
                page?: number;
                /** @description 每页数量 */
                pageSize?: number;
            };
            header?: never;
            path: {
                id: number;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_addChunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddChunkDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_removeChunks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteChunkDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_updateChunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                documentId: string;
                chunkId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChunkDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_toggleDocumentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleDocumentStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_keywordTagStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeBaseController_getMetadataSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_parseDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseDocumentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    KnowledgeBaseController_stopParseDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseDocumentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
