/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/authentication/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新令牌 */
        post: operations["AuthenticationController_refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/authentication/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录 */
        post: operations["AuthenticationController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/authentication/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 注册 */
        post: operations["AuthenticationController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/user/changePassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改自身密码 */
        patch: operations["UserController_changePassword"];
        trace?: never;
    };
    "/api/system/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户列表（分页） */
        get: operations["UserController_findWithPagination"];
        put?: never;
        /** 创建用户 */
        post: operations["UserController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取单个用户信息 */
        get: operations["UserController_findOne"];
        put?: never;
        post?: never;
        /** 删除用户 */
        delete: operations["UserController_delete"];
        options?: never;
        head?: never;
        /** 更新用户 */
        patch: operations["UserController_update"];
        trace?: never;
    };
    "/api/system/user/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有用户列表 */
        get: operations["UserController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/user/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前登录用户信息 */
        get: operations["UserController_findSelf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/user/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前登录用户权限码 */
        get: operations["UserController_findSelfCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/user/resetPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 管理员修改用户密码 */
        patch: operations["UserController_resetPassword"];
        trace?: never;
    };
    "/api/system/user/uploadAvatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传用户头像 */
        post: operations["UserController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/dept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取部门列表 */
        get: operations["DeptController_findAll"];
        put?: never;
        /** 创建部门 */
        post: operations["DeptController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/dept/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取部门详情 */
        get: operations["DeptController_findOne"];
        put?: never;
        post?: never;
        /** 删除部门 */
        delete: operations["DeptController_delete"];
        options?: never;
        head?: never;
        /** 更新部门 */
        patch: operations["DeptController_update"];
        trace?: never;
    };
    "/api/system/dict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取字典列表 */
        get: operations["DictController_findAll"];
        put?: never;
        /** 创建字典 */
        post: operations["DictController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/dict/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取字典数据列表 */
        get: operations["DictController_findAllData"];
        put?: never;
        /** 创建字典数据 */
        post: operations["DictController_createData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/dict/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取字典详情 */
        get: operations["DictController_findOne"];
        put?: never;
        post?: never;
        /** 删除字典 */
        delete: operations["DictController_delete"];
        options?: never;
        head?: never;
        /** 更新字典 */
        patch: operations["DictController_update"];
        trace?: never;
    };
    "/api/system/dict/data/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取字典数据详情 */
        get: operations["DictController_findOneData"];
        put?: never;
        post?: never;
        /** 删除字典数据 */
        delete: operations["DictController_deleteData"];
        options?: never;
        head?: never;
        /** 更新字典数据 */
        patch: operations["DictController_updateData"];
        trace?: never;
    };
    "/api/system/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取菜单列表 */
        get: operations["MenuController_findAll"];
        put?: never;
        /** 创建菜单 */
        post: operations["MenuController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/menu/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取菜单详情 */
        get: operations["MenuController_findOne"];
        put?: never;
        post?: never;
        /** 删除菜单 */
        delete: operations["MenuController_delete"];
        options?: never;
        head?: never;
        /** 更新菜单 */
        patch: operations["MenuController_update"];
        trace?: never;
    };
    "/api/system/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取权限列表 */
        get: operations["RoleController_findWithPagination"];
        put?: never;
        /** 创建权限 */
        post: operations["RoleController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/role/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取权限详情 */
        get: operations["RoleController_findOne"];
        put?: never;
        post?: never;
        /** 删除权限 */
        delete: operations["RoleController_delete"];
        options?: never;
        head?: never;
        /** 更新权限 */
        patch: operations["RoleController_update"];
        trace?: never;
    };
    "/api/system/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取岗位列表 */
        get: operations["PostController_findWithPagination"];
        put?: never;
        /** 创建岗位 */
        post: operations["PostController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/post/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取岗位详情 */
        get: operations["PostController_findOne"];
        put?: never;
        post?: never;
        /** 删除岗位 */
        delete: operations["PostController_delete"];
        options?: never;
        head?: never;
        /** 更新岗位 */
        patch: operations["PostController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RefreshTokenDto: {
            refreshToken: string;
        };
        SignInEntity: {
            accessToken: string;
            refreshToken: string;
        };
        SignInDto: {
            /**
             * @description 密码
             * @example 123456
             */
            password: string;
            /**
             * @description 账号
             * @example admin
             */
            username: string;
        };
        SignUpDto: {
            /**
             * @description 账号
             * @example admin
             */
            username: string;
            /**
             * @description 昵称
             * @example 管理员
             */
            nickname?: string;
            /**
             * @description 密码
             * @example 123456
             */
            password: string;
        };
        ChangePasswordDto: {
            oldPassword: string;
            password: string;
        };
        RoleEntity: {
            /** Format: date-time */
            createdAt: string;
            id: number;
            name: string;
            order: number;
            remark: string;
            status: boolean;
            /** Format: date-time */
            updatedAt: string;
            value: string;
        };
        UserEntity: {
            avatar: string;
            /** Format: date-time */
            createdAt: string;
            deptId: number | null;
            email: string;
            id: number;
            isAdmin: boolean;
            isDeptAdmin: boolean;
            nickname: string;
            phoneNumber: string;
            remark: string;
            roleIds: number[];
            roles: components["schemas"]["RoleEntity"][];
            sex: string;
            status: boolean;
            /** Format: date-time */
            updatedAt: string;
            username: string;
        };
        CreateUserDto: {
            /**
             * Format: uri
             * @description 头像
             * @example http://xxx.com/xxx.jpg
             */
            avatar?: string;
            /**
             * @description 部门ID
             * @example 1
             */
            deptId?: number;
            /**
             * Format: email
             * @description 邮箱
             * @example xxx@qq.com
             */
            email?: string;
            /**
             * @description 是否是部门管理员
             * @default false
             * @example true
             */
            isDeptAdmin: boolean;
            /**
             * @description 菜单ID
             * @example [
             *       1,
             *       2
             *     ]
             */
            menuIds?: number[];
            /**
             * @description 昵称
             * @example 管理员
             */
            nickname?: string;
            /**
             * @description 密码
             * @example 123456
             */
            password: string;
            /**
             * @description 手机号
             * @example 18888888888
             */
            phoneNumber?: string;
            /**
             * @description 岗位ID
             * @example 1
             */
            postId?: number;
            /**
             * @description 备注
             * @example 备注
             */
            remark?: string;
            /**
             * @description 角色ID
             * @example [
             *       1,
             *       2
             *     ]
             */
            roleIds?: number[];
            /**
             * @description 性别 0: 女 1: 男 2: 未知
             * @default 1
             * @example 1
             */
            sex: string;
            /**
             * @description 状态 false: 禁用 true: 启用
             * @default true
             * @example true
             */
            status: boolean;
            /**
             * @description 账号
             * @example admin
             */
            username: string;
        };
        PaginateResponse: {
            /**
             * @description 页码
             * @default 1
             * @example 1
             */
            current: number;
            /**
             * @description 每页数量
             * @default 10
             * @example 10
             */
            pageSize: number;
        };
        AdminChangePasswordDto: {
            id: number;
            password: string;
        };
        UpdateUserDto: {
            /**
             * Format: uri
             * @description 头像
             * @example http://xxx.com/xxx.jpg
             */
            avatar?: string;
            /**
             * @description 部门ID
             * @example 1
             */
            deptId?: number;
            /**
             * Format: email
             * @description 邮箱
             * @example xxx@qq.com
             */
            email?: string;
            /**
             * @description 是否是部门管理员
             * @default false
             * @example true
             */
            isDeptAdmin: boolean;
            /**
             * @description 菜单ID
             * @example [
             *       1,
             *       2
             *     ]
             */
            menuIds?: number[];
            /**
             * @description 昵称
             * @example 管理员
             */
            nickname?: string;
            /**
             * @description 密码
             * @example 123456
             */
            password?: string;
            /**
             * @description 手机号
             * @example 18888888888
             */
            phoneNumber?: string;
            /**
             * @description 岗位ID
             * @example 1
             */
            postId?: number;
            /**
             * @description 备注
             * @example 备注
             */
            remark?: string;
            /**
             * @description 角色ID
             * @example [
             *       1,
             *       2
             *     ]
             */
            roleIds?: number[];
            /**
             * @description 性别 0: 女 1: 男 2: 未知
             * @default 1
             * @example 1
             */
            sex: string;
            /**
             * @description 状态 false: 禁用 true: 启用
             * @default true
             * @example true
             */
            status: boolean;
            /**
             * @description 账号
             * @example admin
             */
            username?: string;
        };
        CreateDeptDto: {
            /**
             * @description 邮箱
             * @example xxx@qq.com
             */
            email?: string;
            /**
             * @description 负责人id
             * @example 1
             */
            leaderId: number;
            /**
             * @description 部门名称
             * @example 技术部
             */
            name: string;
            /**
             * @description 排序
             * @example 1
             */
            order?: number;
            /** @description 上级部门ID */
            parentId?: number;
            /**
             * @description 负责人电话
             * @example 13000000000
             */
            phone?: string;
        };
        DeptEntity: {
            children?: components["schemas"]["DeptEntity"][] | null;
            /** Format: date-time */
            createdAt: string;
            email: string;
            id: number;
            leader: string | null;
            leaderId: number | null;
            name: string;
            order: number;
            parentId: number | null;
            phone: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateDeptDto: {
            /**
             * @description 邮箱
             * @example xxx@qq.com
             */
            email?: string;
            /**
             * @description 负责人id
             * @example 1
             */
            leaderId?: number;
            /**
             * @description 部门名称
             * @example 技术部
             */
            name?: string;
            /**
             * @description 排序
             * @example 1
             */
            order?: number;
            /** @description 上级部门ID */
            parentId?: number;
            /**
             * @description 负责人电话
             * @example 13000000000
             */
            phone?: string;
        };
        CreateDictDto: {
            /**
             * @description 字典名称
             * @example 性别
             */
            name: string;
            /**
             * @description 备注
             * @example 备注
             */
            remark?: string;
            /**
             * @description 状态
             * @example true
             */
            status?: boolean;
            /**
             * @description 字典值
             * @example 1
             */
            value: string;
        };
        DictEntity: {
            /** Format: date-time */
            createdAt: string;
            id: number;
            name: string;
            remark: string;
            status: boolean;
            /** Format: date-time */
            updatedAt: string;
            value: string;
        };
        CreateDictDataDto: {
            /**
             * @description 字典ID
             * @example 1
             */
            dictId: number;
            /**
             * @description 字典数据名称
             * @example 性别
             */
            name: string;
            /**
             * @description 排序
             * @example 1
             */
            order?: number;
            /**
             * @description 备注
             * @example 备注
             */
            remark?: string;
            /**
             * @description 状态 false: 禁用 true: 启用
             * @default true
             * @example true
             */
            status: boolean;
            /**
             * @description 字典数据值
             * @example 1
             */
            value: string;
        };
        DictDataEntity: {
            /** Format: date-time */
            createdAt: string;
            dictId: number;
            id: number;
            name: string;
            order: number;
            remark: string;
            status: boolean;
            updateBy: string | null;
            /** Format: date-time */
            updatedAt: string;
            value: string;
        };
        UpdateDictDto: {
            /**
             * @description 字典名称
             * @example 性别
             */
            name?: string;
            /**
             * @description 备注
             * @example 备注
             */
            remark?: string;
            /**
             * @description 状态
             * @example true
             */
            status?: boolean;
            /**
             * @description 字典值
             * @example 1
             */
            value?: string;
        };
        UpdateDictDataDto: {
            /**
             * @description 字典ID
             * @example 1
             */
            dictId?: number;
            /**
             * @description 字典数据名称
             * @example 性别
             */
            name?: string;
            /**
             * @description 排序
             * @example 1
             */
            order?: number;
            /**
             * @description 备注
             * @example 备注
             */
            remark?: string;
            /**
             * @description 状态 false: 禁用 true: 启用
             * @default true
             * @example true
             */
            status: boolean;
            /**
             * @description 字典数据值
             * @example 1
             */
            value?: string;
        };
        CreateMenuDto: {
            /**
             * @description 激活菜单图标
             * @example i-line-md:external-link
             */
            activeIcon?: string;
            /**
             * @description 作为路由时，需要激活的菜单的Path
             * @example /system
             */
            activePath?: string;
            /**
             * @description 固定在标签栏
             * @default true
             * @example true
             */
            affixTab: boolean;
            /**
             * @description 在标签栏固定的顺序
             * @default 1
             * @example 1
             */
            affixTabOrder: number;
            /**
             * @description 徽标内容 (当徽标类型为normal时有效)
             * @example new
             */
            badge?: string;
            /**
             * @description 徽标类型
             * @example dot
             */
            badgeType?: string;
            /**
             * @description 徽标颜色
             * @example default
             */
            badgeVariants?: string;
            /**
             * @description 在菜单中隐藏下级
             * @default false
             * @example false
             */
            hideChildrenInMenu: boolean;
            /**
             * @description 在面包屑中隐藏
             * @default false
             * @example false
             */
            hideInBreadcrumb: boolean;
            /**
             * @description 在菜单中隐藏
             * @default false
             * @example false
             */
            hideInMenu: boolean;
            /**
             * @description 在标签栏中隐藏
             * @default false
             * @example false
             */
            hideInTab: boolean;
            /**
             * @description 菜单图标
             * @example i-line-md:external-link
             */
            icon?: string;
            /**
             * @description 内嵌Iframe的URL
             * @example www.example.com
             */
            iframeSrc?: string;
            /**
             * @description 是否缓存页面
             * @default false
             * @example false
             */
            keepAlive: boolean;
            /**
             * @description 外链页面的URL
             * @example www.example.com
             */
            link?: string;
            /**
             * @description 同一个路由最大打开的标签数
             * @default 1
             * @example 1
             */
            maxNumOfOpenTabs: number;
            /**
             * @description 菜单名称
             * @example 系统管理
             */
            name: string;
            /**
             * @description 无需基础布局
             * @default false
             * @example false
             */
            noBasicLayout: boolean;
            /**
             * @description 是否在新窗口打开
             * @default false
             * @example false
             */
            openInNewWindow: boolean;
            /**
             * @description 排序
             * @default 1
             * @example 1
             */
            order: number;
            /**
             * @description 父级菜单id
             * @example 0
             */
            parentId?: number;
            /**
             * @description 菜单路径
             * @example /system
             */
            path?: string;
            /**
             * @description 权限标识
             * @example system:menu:list
             */
            permission?: string;
            /**
             * @description 额外的路由参数
             * @example /:id
             */
            query?: string;
            /**
             * @description 重定向
             * @example /system
             */
            redirect?: string;
            /**
             * @description 状态 false: 禁用 true: 启用
             * @default true
             * @example true
             */
            status: boolean;
            /**
             * @description 菜单标题 (配置页面的标题,配合国际化使用)
             * @example "system.title
             */
            title?: string;
            /**
             * @description 菜单类别
             * @example menu
             */
            type: string;
        };
        MenuEntity: {
            activeIcon: string | null;
            activePath: string | null;
            affixTab: boolean;
            affixTabOrder: number;
            badge: string | null;
            badgeType: string;
            badgeVariants: string;
            children?: components["schemas"]["MenuEntity"][] | null;
            hideChildrenInMenu: boolean;
            hideInBreadcrumb: boolean;
            hideInMenu: boolean;
            hideInTab: boolean;
            icon: string | null;
            id: number;
            iframeSrc: string | null;
            keepAlive: boolean;
            link: string | null;
            maxNumOfOpenTabs: number | null;
            name: string;
            noBasicLayout: boolean;
            openInNewWindow: boolean;
            order: number;
            parentId: number | null;
            path: string;
            permission: string;
            query: string | null;
            redirect: string | null;
            status: boolean;
            title: string | null;
            type: string;
        };
        UpdateMenuDto: {
            /**
             * @description 激活菜单图标
             * @example i-line-md:external-link
             */
            activeIcon?: string;
            /**
             * @description 作为路由时，需要激活的菜单的Path
             * @example /system
             */
            activePath?: string;
            /**
             * @description 固定在标签栏
             * @default true
             * @example true
             */
            affixTab: boolean;
            /**
             * @description 在标签栏固定的顺序
             * @default 1
             * @example 1
             */
            affixTabOrder: number;
            /**
             * @description 徽标内容 (当徽标类型为normal时有效)
             * @example new
             */
            badge?: string;
            /**
             * @description 徽标类型
             * @example dot
             */
            badgeType?: string;
            /**
             * @description 徽标颜色
             * @example default
             */
            badgeVariants?: string;
            /**
             * @description 在菜单中隐藏下级
             * @default false
             * @example false
             */
            hideChildrenInMenu: boolean;
            /**
             * @description 在面包屑中隐藏
             * @default false
             * @example false
             */
            hideInBreadcrumb: boolean;
            /**
             * @description 在菜单中隐藏
             * @default false
             * @example false
             */
            hideInMenu: boolean;
            /**
             * @description 在标签栏中隐藏
             * @default false
             * @example false
             */
            hideInTab: boolean;
            /**
             * @description 菜单图标
             * @example i-line-md:external-link
             */
            icon?: string;
            /**
             * @description 内嵌Iframe的URL
             * @example www.example.com
             */
            iframeSrc?: string;
            /**
             * @description 是否缓存页面
             * @default false
             * @example false
             */
            keepAlive: boolean;
            /**
             * @description 外链页面的URL
             * @example www.example.com
             */
            link?: string;
            /**
             * @description 同一个路由最大打开的标签数
             * @default 1
             * @example 1
             */
            maxNumOfOpenTabs: number;
            /**
             * @description 菜单名称
             * @example 系统管理
             */
            name: string;
            /**
             * @description 无需基础布局
             * @default false
             * @example false
             */
            noBasicLayout: boolean;
            /**
             * @description 是否在新窗口打开
             * @default false
             * @example false
             */
            openInNewWindow: boolean;
            /**
             * @description 排序
             * @default 1
             * @example 1
             */
            order: number;
            /**
             * @description 父级菜单id
             * @example 0
             */
            parentId?: number;
            /**
             * @description 菜单路径
             * @example /system
             */
            path?: string;
            /**
             * @description 权限标识
             * @example system:menu:list
             */
            permission?: string;
            /**
             * @description 额外的路由参数
             * @example /:id
             */
            query?: string;
            /**
             * @description 重定向
             * @example /system
             */
            redirect?: string;
            /**
             * @description 状态 false: 禁用 true: 启用
             * @default true
             * @example true
             */
            status: boolean;
            /**
             * @description 菜单标题 (配置页面的标题,配合国际化使用)
             * @example "system.title
             */
            title?: string;
            /**
             * @description 菜单类别
             * @example menu
             */
            type: string;
        };
        CreateRoleDto: {
            /**
             * @description 菜单ID
             * @example [
             *       1,
             *       2
             *     ]
             */
            menuIds: number[];
            /**
             * @description 权限名称
             * @example 管理员
             */
            name: string;
            /**
             * @description 排序
             * @default 0
             * @example 0
             */
            order: number;
            /**
             * @description 备注
             * @example 备注
             */
            remark?: string;
            /**
             * @description 权限值
             * @example admin
             */
            value: string;
        };
        UpdateRoleDto: {
            /**
             * @description 菜单ID
             * @example [
             *       1,
             *       2
             *     ]
             */
            menuIds?: number[];
            /**
             * @description 权限名称
             * @example 管理员
             */
            name?: string;
            /**
             * @description 排序
             * @default 0
             * @example 0
             */
            order: number;
            /**
             * @description 备注
             * @example 备注
             */
            remark?: string;
            /**
             * @description 权限值
             * @example admin
             */
            value?: string;
        };
        CreatePostDto: {
            /**
             * @description 岗位编码
             * @example tech
             */
            code: string;
            /**
             * @description 岗位名称
             * @example 技术部
             */
            name: string;
            /**
             * @description 排序
             * @example 1
             */
            order?: number;
            /**
             * @description 备注
             * @example 这是一个技术部
             */
            remark?: string;
        };
        PostEntity: {
            code: string;
            /** Format: date-time */
            createdAt: string;
            id: number;
            name: string;
            order: number;
            remark: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdatePostDto: {
            /**
             * @description 岗位编码
             * @example tech
             */
            code?: string;
            /**
             * @description 岗位名称
             * @example 技术部
             */
            name?: string;
            /**
             * @description 排序
             * @example 1
             */
            order?: number;
            /**
             * @description 备注
             * @example 这是一个技术部
             */
            remark?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthenticationController_refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInEntity"];
                };
            };
        };
    };
    AuthenticationController_signIn: {
        parameters: {
            query?: never;
            header?: {
                "X-Real-IP"?: string;
                "User-Agent"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInEntity"];
                };
            };
        };
    };
    AuthenticationController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpDto"];
            };
        };
        responses: {
            /** @description 用户注册成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    UserController_findWithPagination: {
        parameters: {
            query?: {
                /** @description 账号 */
                username?: string;
                /** @description 昵称 */
                nickname?: string;
                /** @description 邮箱 */
                email?: string;
                /** @description 手机号 */
                phoneNumber?: string;
                /** @description 页码 */
                current?: number;
                /** @description 每页数量 */
                pageSize?: number;
                createdAt?: string[];
                /** @description 排序顺序 asc 正序, desc 倒序 */
                order?: "asc" | "desc";
                updatedAt?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginateResponse"] & {
                        /** @default 1 */
                        currentPage: number;
                        /** @default 0 */
                        totalCount: number;
                        /** @default 0 */
                        pageCount: number;
                        /** @default [] */
                        list: components["schemas"]["UserEntity"][];
                    };
                };
            };
        };
    };
    UserController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    UserController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    UserController_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Real-IP"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    UserController_findAll: {
        parameters: {
            query?: {
                /** @description 账号 */
                username?: string;
                /** @description 昵称 */
                nickname?: string;
                /** @description 邮箱 */
                email?: string;
                /** @description 手机号 */
                phoneNumber?: string;
                /** @description 页码 */
                current?: number;
                /** @description 每页数量 */
                pageSize?: number;
                createdAt?: string[];
                /** @description 排序顺序 asc 正序, desc 倒序 */
                order?: "asc" | "desc";
                updatedAt?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"][];
                };
            };
        };
    };
    UserController_findSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    UserController_findSelfCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    UserController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminChangePasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    UserController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeptController_findAll: {
        parameters: {
            query?: {
                /** @description 部门名称 */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeptEntity"][];
                };
            };
        };
    };
    DeptController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeptDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeptEntity"];
                };
            };
        };
    };
    DeptController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeptEntity"];
                };
            };
        };
    };
    DeptController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeptController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeptDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeptEntity"];
                };
            };
        };
    };
    DictController_findAll: {
        parameters: {
            query?: {
                /** @description 字典名称 */
                name?: string;
                /** @description 字典值 */
                value?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictEntity"][];
                };
            };
        };
    };
    DictController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDictDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictEntity"];
                };
            };
        };
    };
    DictController_findAllData: {
        parameters: {
            query?: {
                /** @description 字典名称 */
                dictName?: string;
                /** @description 字典名称值 */
                dictValue?: string;
                /** @description 字典数据名称 */
                name?: string;
                /** @description 字典数据值 */
                value?: string;
                /** @description 字典ID */
                dictId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictDataEntity"][];
                };
            };
        };
    };
    DictController_createData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDictDataDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictDataEntity"];
                };
            };
        };
    };
    DictController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictEntity"];
                };
            };
        };
    };
    DictController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DictController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDictDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictEntity"];
                };
            };
        };
    };
    DictController_findOneData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictDataEntity"];
                };
            };
        };
    };
    DictController_deleteData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DictController_updateData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDictDataDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictDataEntity"];
                };
            };
        };
    };
    MenuController_findAll: {
        parameters: {
            query?: {
                /** @description 菜单名称 */
                name?: string;
                /** @description 菜单路径 */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuEntity"][];
                };
            };
        };
    };
    MenuController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMenuDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuEntity"];
                };
            };
        };
    };
    MenuController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuEntity"];
                };
            };
        };
    };
    MenuController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MenuController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMenuDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuEntity"];
                };
            };
        };
    };
    RoleController_findWithPagination: {
        parameters: {
            query?: {
                /** @description 权限名称 */
                name?: string;
                /** @description 权限值 */
                value?: string;
                /** @description 页码 */
                current?: number;
                /** @description 每页数量 */
                pageSize?: number;
                createdAt?: string[];
                /** @description 排序顺序 asc 正序, desc 倒序 */
                order?: "asc" | "desc";
                updatedAt?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginateResponse"] & {
                        /** @default 1 */
                        currentPage: number;
                        /** @default 0 */
                        totalCount: number;
                        /** @default 0 */
                        pageCount: number;
                        /** @default [] */
                        list: components["schemas"]["RoleEntity"][];
                    };
                };
            };
        };
    };
    RoleController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleEntity"];
                };
            };
        };
    };
    RoleController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleEntity"];
                };
            };
        };
    };
    RoleController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoleController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleEntity"];
                };
            };
        };
    };
    PostController_findWithPagination: {
        parameters: {
            query?: {
                /** @description 岗位名称 */
                name?: string;
                /** @description 岗位编码 */
                code?: string;
                /** @description 页码 */
                current?: number;
                /** @description 每页数量 */
                pageSize?: number;
                createdAt?: string[];
                /** @description 排序顺序 asc 正序, desc 倒序 */
                order?: "asc" | "desc";
                updatedAt?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginateResponse"] & {
                        /** @default 1 */
                        currentPage: number;
                        /** @default 0 */
                        totalCount: number;
                        /** @default 0 */
                        pageCount: number;
                        /** @default [] */
                        list: components["schemas"]["PostEntity"][];
                    };
                };
            };
        };
    };
    PostController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostEntity"];
                };
            };
        };
    };
    PostController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostEntity"];
                };
            };
        };
    };
    PostController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePostDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostEntity"];
                };
            };
        };
    };
}
