/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/weekly-report/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取周报历史列表（不含正文） */
        get: operations["WeeklyReportController_findAll"];
        put?: never;
        /** 生成周报（同步等待对方服务返回，耗时可能数分钟） */
        post: operations["WeeklyReportController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weekly-report/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取周报详情 */
        get: operations["WeeklyReportController_findOne"];
        put?: never;
        post?: never;
        /** 删除周报 */
        delete: operations["WeeklyReportController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenerateWeeklyReportDto: {
            /**
             * @description 分公司（字典 weeklyReport.branch 的键值）
             * @example 华东分公司
             */
            branch: string;
            /**
             * @description 报告日期
             * @example 2025-09-20
             */
            reportDate: string;
            /**
             * @description 报告类型（字典 weeklyReport.type 的键值）
             * @example weekly
             */
            reportType: string;
        };
        PaginateResponse: {
            /**
             * @description 页码
             *     @default 1
             * @default 1
             * @example 1
             */
            current: number;
            /**
             * @description 每页数量
             *     @default 10
             * @default 10
             * @example 10
             */
            pageSize: number;
        };
        WeeklyReportEntity: {
            /** @description 分公司 */
            branch: string;
            /** @description 报告正文（Markdown） */
            content: string;
            /**
             * Format: date-time
             * @description 生成时间
             */
            createdAt: string;
            /** @description 主键 ID */
            id: number;
            /**
             * @description 报告日期（纯日期串，不带时区）
             * @example 2025-09-20
             */
            reportDate: string;
            /** @description 报告类型 */
            reportType: string;
            /** @description 生成人 ID */
            userId: number;
        };
        WeeklyReportListItemEntity: {
            /** @description 分公司 */
            branch: string;
            /**
             * Format: date-time
             * @description 生成时间
             */
            createdAt: string;
            /** @description 主键 ID */
            id: number;
            /**
             * @description 报告日期（纯日期串，不带时区）
             * @example 2025-09-20
             */
            reportDate: string;
            /** @description 报告类型 */
            reportType: string;
            /** @description 生成人 ID */
            userId: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    WeeklyReportController_findAll: {
        parameters: {
            query?: {
                /**
                 * @description 页码
                 *     @default 1
                 */
                current?: number;
                /**
                 * @description 每页数量
                 *     @default 10
                 */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginateResponse"] & {
                        /** @default 1 */
                        currentPage: number;
                        /** @default [] */
                        list: components["schemas"]["WeeklyReportListItemEntity"][];
                        /** @default 0 */
                        pageCount: number;
                        /** @default 0 */
                        totalCount: number;
                    };
                };
            };
        };
    };
    WeeklyReportController_generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateWeeklyReportDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReportEntity"];
                };
            };
        };
    };
    WeeklyReportController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReportEntity"];
                };
            };
        };
    };
    WeeklyReportController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
