/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/monitor/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行信息 */
        get: operations["InfoController_systemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/login-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取登录日志列表 */
        get: operations["LoginLogController_findWithPagination"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/login-log/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取登录日志详情 */
        get: operations["LoginLogController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/operation-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取操作日志列表 */
        get: operations["OperationLogController_findWithPagination"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/operation-log/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取操作日志详情 */
        get: operations["OperationLogController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthEntity: {
            /**
             * @description 服务状态
             * @example ok
             */
            status: string;
            /**
             * @description 时间戳
             * @example 2026-04-04T10:00:00.000Z
             */
            timestamp: string;
            /**
             * @description 后端版本号
             * @example 0.1.0
             */
            version: string;
        };
        InfoEntity: {
            cpu: {
                brand: string;
                cores: number;
                manufacturer: string;
                speed: string;
            };
            memory: {
                free: string;
                total: string;
                usage: string;
                used: string;
            };
            osInfo: {
                arch: string;
                hostname: string;
                platform: string;
                release: string;
            };
        };
        LoginLogEntity: {
            address: string;
            browser: string;
            /** Format: date-time */
            createdAt: string;
            id: number;
            ip: string;
            /** Format: date-time */
            loginTime: string;
            message: string;
            os: string;
            status: boolean;
            username: string;
        };
        OperationLogEntity: {
            address: string;
            businessType: number;
            /** Format: date-time */
            createdAt: string;
            id: number;
            ip: string;
            module: string;
            title: string;
            username: string;
        };
        PaginateResponse: {
            /**
             * @description 页码
             *     @default 1
             * @default 1
             * @example 1
             */
            current: number;
            /**
             * @description 每页数量
             *     @default 10
             * @default 10
             * @example 10
             */
            pageSize: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEntity"];
                };
            };
        };
    };
    InfoController_systemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoEntity"];
                };
            };
        };
    };
    LoginLogController_findWithPagination: {
        parameters: {
            query?: {
                /** @description 用户名 */
                username?: string;
                /**
                 * @description 页码
                 *     @default 1
                 */
                current?: number;
                /**
                 * @description 每页数量
                 *     @default 10
                 */
                pageSize?: number;
                createdAt?: string[];
                /** @description 排序顺序 asc 正序, desc 倒序 */
                order?: "asc" | "desc";
                updatedAt?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginateResponse"] & {
                        /** @default 1 */
                        currentPage: number;
                        /** @default [] */
                        list: components["schemas"]["LoginLogEntity"][];
                        /** @default 0 */
                        pageCount: number;
                        /** @default 0 */
                        totalCount: number;
                    };
                };
            };
        };
    };
    LoginLogController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginLogEntity"];
                };
            };
        };
    };
    OperationLogController_findWithPagination: {
        parameters: {
            query?: {
                username?: string;
                businessType?: number;
                module?: string;
                /**
                 * @description 页码
                 *     @default 1
                 */
                current?: number;
                /**
                 * @description 每页数量
                 *     @default 10
                 */
                pageSize?: number;
                createdAt?: string[];
                /** @description 排序顺序 asc 正序, desc 倒序 */
                order?: "asc" | "desc";
                updatedAt?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginateResponse"] & {
                        /** @default 1 */
                        currentPage: number;
                        /** @default [] */
                        list: components["schemas"]["OperationLogEntity"][];
                        /** @default 0 */
                        pageCount: number;
                        /** @default 0 */
                        totalCount: number;
                    };
                };
            };
        };
    };
    OperationLogController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationLogEntity"];
                };
            };
        };
    };
}
