/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/403': RouteRecordInfo<
      '/403',
      '/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/assistant/': RouteRecordInfo<
      '/assistant/',
      '/assistant',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/assistant/chat/[id]': RouteRecordInfo<
      '/assistant/chat/[id]',
      '/assistant/chat/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dashboard/analytics': RouteRecordInfo<
      '/dashboard/analytics',
      '/dashboard/analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/chat': RouteRecordInfo<
      '/dashboard/chat',
      '/dashboard/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/knowledgeBase/': RouteRecordInfo<
      '/knowledgeBase/',
      '/knowledgeBase',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/knowledgeBase/detail/[id]': RouteRecordInfo<
      '/knowledgeBase/detail/[id]',
      '/knowledgeBase/detail/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.page.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/[...all].page.vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/views/403.page.vue': {
      routes:
        | '/403'
      views:
        | never
    }
    'src/views/assistant/index.page.vue': {
      routes:
        | '/assistant/'
      views:
        | never
    }
    'src/views/assistant/chat/[id].page.vue': {
      routes:
        | '/assistant/chat/[id]'
      views:
        | never
    }
    'src/views/dashboard/analytics.page.vue': {
      routes:
        | '/dashboard/analytics'
      views:
        | never
    }
    'src/views/dashboard/chat.page.vue': {
      routes:
        | '/dashboard/chat'
      views:
        | never
    }
    'src/views/knowledgeBase/index.page.vue': {
      routes:
        | '/knowledgeBase/'
      views:
        | never
    }
    'src/views/knowledgeBase/detail/[id].page.vue': {
      routes:
        | '/knowledgeBase/detail/[id]'
      views:
        | never
    }
    'src/views/login/index.page.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
