/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all].page': RouteRecordInfo<
      '/[...all].page',
      '/:all(.*)/page',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/403.page': RouteRecordInfo<
      '/403.page',
      '/403/page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/assistant/chat/[id].page': RouteRecordInfo<
      '/assistant/chat/[id].page',
      '/assistant/chat/:id/page',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/assistant/index.page': RouteRecordInfo<
      '/assistant/index.page',
      '/assistant/index/page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/analytics.page': RouteRecordInfo<
      '/dashboard/analytics.page',
      '/dashboard/analytics/page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/chat.page': RouteRecordInfo<
      '/dashboard/chat.page',
      '/dashboard/chat/page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/knowledgeBase/detail/[id].page': RouteRecordInfo<
      '/knowledgeBase/detail/[id].page',
      '/knowledgeBase/detail/:id/page',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/knowledgeBase/index.page': RouteRecordInfo<
      '/knowledgeBase/index.page',
      '/knowledgeBase/index/page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/form': RouteRecordInfo<
      '/login/form',
      '/login/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/toolbar': RouteRecordInfo<
      '/login/toolbar',
      '/login/toolbar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/[...all].page.vue': {
      routes:
        | '/[...all].page'
      views:
        | never
    }
    'src/views/403.page.vue': {
      routes:
        | '/403.page'
      views:
        | never
    }
    'src/views/assistant/chat/[id].page.vue': {
      routes:
        | '/assistant/chat/[id].page'
      views:
        | never
    }
    'src/views/assistant/index.page.vue': {
      routes:
        | '/assistant/index.page'
      views:
        | never
    }
    'src/views/dashboard/analytics.page.vue': {
      routes:
        | '/dashboard/analytics.page'
      views:
        | never
    }
    'src/views/dashboard/chat.page.vue': {
      routes:
        | '/dashboard/chat.page'
      views:
        | never
    }
    'src/views/knowledgeBase/detail/[id].page.vue': {
      routes:
        | '/knowledgeBase/detail/[id].page'
      views:
        | never
    }
    'src/views/knowledgeBase/index.page.vue': {
      routes:
        | '/knowledgeBase/index.page'
      views:
        | never
    }
    'src/views/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/views/login/form.vue': {
      routes:
        | '/login/form'
      views:
        | never
    }
    'src/views/login/toolbar.vue': {
      routes:
        | '/login/toolbar'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
